import 'dart:async';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';
import 'package:file_picker/file_picker.dart';
import 'package:streamapp/features/video_player/data/models/detection_result.dart';
import 'package:streamapp/features/video_player/data/services/yolo_detector.dart';
import 'package:streamapp/features/video_player/presentation/widgets/detection_painter.dart';
import 'package:subtitle/subtitle.dart';
import 'package:http/http.dart' as http;
import 'dart:convert' show utf8;

/// =====================
/// STRING EXTENSION FOR HTML PARSING
/// =====================

extension HtmlParser on String {
  String parseHtmlString() {
    String result = this;
    result = result.replaceAll(RegExp(r'<br\s*/?>'), '\n');
    result = result.replaceAll(RegExp(r'</p>\s*<p>'), '\n');
    result = result.replaceAll(RegExp(r'<[^>]*>'), '');
    result = result
        .replaceAll('&amp;', '&')
        .replaceAll('&lt;', '<')
        .replaceAll('&gt;', '>')
        .replaceAll('&quot;', '"')
        .replaceAll('&#39;', "'")
        .replaceAll('&apos;', "'")
        .replaceAll('&nbsp;', ' ')
        .replaceAll('&#160;', ' ');
    result = result
        .split('\n')
        .map((line) => line.trim())
        .where((line) => line.isNotEmpty)
        .join('\n');
    return result.trim();
  }
}

/// =====================
/// MODELS
/// =====================

class VideoStream {
  final String url;
  final String resolution;
  final int bitrate;

  VideoStream.fromJson(Map<String, dynamic> json)
      : url = json['content'],
        resolution = json['resolution'] ?? '',
        bitrate = json['bitrate'] ?? 0;
}

class AudioStream {
  final String url;
  final int bitrate;
  final String? language;

  AudioStream.fromJson(Map<String, dynamic> json)
      : url = json['content'],
        bitrate = json['bitrate'] ?? 0,
        language = json['language'];
}

class SubtitleTrack {
  final String url;
  final String locale;
  final bool autoGenerated;
  final SubtitleType format;

  SubtitleTrack({
    required this.url,
    required this.locale,
    required this.autoGenerated,
    required this.format,
  });

  factory SubtitleTrack.fromJson(Map<String, dynamic> json) {
    final url = json['content'] ?? '';
    SubtitleType format = SubtitleType.vtt;

    if (url.contains('fmt=vtt') || url.endsWith('.vtt')) {
      format = SubtitleType.vtt;
    } else if (url.contains('fmt=ttml') ||
        url.endsWith('.ttml') ||
        url.endsWith('.xml')) {
      format = SubtitleType.ttml;
    } else if (url.endsWith('.srt')) {
      format = SubtitleType.srt;
    }

    return SubtitleTrack(
      url: url,
      locale: json['locale'] ?? 'unknown',
      autoGenerated: json['autoGenerated'] ?? false,
      format: format,
    );
  }

  String get label {
    String formatName = format.toString().split('.').last.toUpperCase();
    return '${locale.toUpperCase()}${autoGenerated ? ' (Auto)' : ''} [$formatName]';
  }
}

class SubtitleConfig {
  final double fontSize;
  final Color textColor;
  final Color backgroundColor;
  final SubtitlePosition position;
  final FontWeight fontWeight;
  final double backgroundOpacity;
  final EdgeInsets padding;
  final bool hasShadow;

  const SubtitleConfig({
    this.fontSize = 18.0,
    this.textColor = Colors.white,
    this.backgroundColor = Colors.black,
    this.position = SubtitlePosition.bottom,
    this.fontWeight = FontWeight.w600,
    this.backgroundOpacity = 0.75,
    this.padding = const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
    this.hasShadow = true,
  });

  SubtitleConfig copyWith({
    double? fontSize,
    Color? textColor,
    Color? backgroundColor,
    SubtitlePosition? position,
    FontWeight? fontWeight,
    double? backgroundOpacity,
    EdgeInsets? padding,
    bool? hasShadow,
  }) {
    return SubtitleConfig(
      fontSize: fontSize ?? this.fontSize,
      textColor: textColor ?? this.textColor,
      backgroundColor: backgroundColor ?? this.backgroundColor,
      position: position ?? this.position,
      fontWeight: fontWeight ?? this.fontWeight,
      backgroundOpacity: backgroundOpacity ?? this.backgroundOpacity,
      padding: padding ?? this.padding,
      hasShadow: hasShadow ?? this.hasShadow,
    );
  }
}

enum SubtitlePosition { top, center, bottom }
enum PlaybackMode { muxed, adaptive, audioOnly }

enum ControlButton {
  playPause,
  rewind,
  forward,
  volume,
  speed,
  settings,
  fullscreen,
  detection,
  subtitle,
  timeline,
}

class VideoDetectionScreen extends StatefulWidget {
  final Map<String, dynamic>? videoJson;
  
  const VideoDetectionScreen({Key? key, this.videoJson}) : super(key: key);

  @override
  State<VideoDetectionScreen> createState() => _VideoDetectionScreenState();
}

class _VideoDetectionScreenState extends State<VideoDetectionScreen>
    with TickerProviderStateMixin {
  // Players
  late final Player _videoPlayer;
  late final VideoController _videoController;
  late final Player _audioPlayer;
  late final Player _detectionPlayer;
  late final VideoController _detectionVideoController;
  
  final YOLODetector _detector = YOLODetector();

  // Streaming data
  late final List<VideoStream> _videoStreams;
  late final List<VideoStream> _videoOnlyStreams;
  late final List<AudioStream> _audioStreams;
  late final List<SubtitleTrack> _subtitleTracks;

  PlaybackMode _mode = PlaybackMode.muxed;
  int _videoIndex = 0;
  int _audioIndex = 0;
  int _subtitleIndex = -1;

  // Subtitle state
  SubtitleController? _subtitleController;
  String _currentSubtitle = '';
  bool _isLoadingSubtitle = false;
  SubtitleConfig _subtitleConfig = const SubtitleConfig();
  SubtitleType? _currentSubtitleFormat;
  StreamSubscription<Duration>? _subtitleSyncSub;

  // Detection state
  final Map<int, List<DetectionResult>> _detectionCache = {};
  List<DetectionResult> _currentDetections = [];
  bool _isDetectionEnabled = false;
  bool _isInitialized = false;
  bool _isProcessing = false;

  // Timers
  Timer? _captureTimer;
  Timer? _syncTimer;
  Timer? _audioSyncTimer;
  Timer? _syncCheckTimer;
  Timer? _hideControlsTimer;

  // Video state
  String? _currentVideoPath;

  // Stats
  double _fps = 0.0;
  int _objectCount = 0;
  int _frameCount = 0;
  String _statusMessage = 'Initializing...';
  int _syncDriftMs = 0;
  final List<double> _fpsHistory = [];
  DateTime? _lastFpsUpdate;
  int _lastLookupKey = -1;

  // UI State
  bool _showControls = true;
  bool _isFullscreen = false;
  final FocusNode _mainFocusNode = FocusNode();

  // Focus management
  ControlButton? _focusedControl;
  bool _isTimelineMode = false;

  // Popup states
  bool _showVolumePopup = false;
  bool _showSpeedPopup = false;
  bool _showSettingsPopup = false;
  
  late AnimationController _volumePopupController;
  late AnimationController _speedPopupController;
  late Animation<double> _volumePopupAnimation;
  late Animation<double> _speedPopupAnimation;

  double _currentVolume = 100;
  double _currentSpeed = 1.0;

  // Settings
  static const int DETECTION_AHEAD_SECONDS = 3;
  static const int CAPTURE_INTERVAL_MS = 50;
  static const int SYNC_INTERVAL_MS = 33;
  static const int SYNC_CHECK_INTERVAL_MS = 1000;
  static const int MAX_DRIFT_MS = 150;
  static const int CACHE_CLEANUP_THRESHOLD = 250;
  static const Duration CONTROLS_HIDE_DURATION = Duration(seconds: 3);

  @override
  void initState() {
    super.initState();
    _initializePlayers();
    _initializeDetector();
    _initializeAnimations();
    _initializeStreamingData();
    _mainFocusNode.requestFocus();
    _startHideTimer();
  }

  void _initializeStreamingData() {
    if (widget.videoJson != null) {
      _videoStreams = (widget.videoJson!['videoStreams'] as List? ?? [])
          .map((e) => VideoStream.fromJson(e))
          .toList()
        ..sort((a, b) => b.bitrate.compareTo(a.bitrate));

      _videoOnlyStreams = (widget.videoJson!['videoOnlyStreams'] as List? ?? [])
          .map((e) => VideoStream.fromJson(e))
          .toList()
        ..sort((a, b) => b.bitrate.compareTo(a.bitrate));

      _audioStreams = (widget.videoJson!['audioStreams'] as List? ?? [])
          .map((e) => AudioStream.fromJson(e))
          .toList()
        ..sort((a, b) => b.bitrate.compareTo(a.bitrate));

      _subtitleTracks = (widget.videoJson!['subtitles'] as List? ?? [])
          .map((e) => SubtitleTrack.fromJson(e))
          .toList();

      // Auto-load video in muxed mode
      if (_videoStreams.isNotEmpty) {
        _openMuxed();
      }
    } else {
      _videoStreams = [];
      _videoOnlyStreams = [];
      _audioStreams = [];
      _subtitleTracks = [];
    }
  }

  void _initializeAnimations() {
    _volumePopupController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 200),
    );
    _speedPopupController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 200),
    );
    _volumePopupAnimation = CurvedAnimation(
      parent: _volumePopupController,
      curve: Curves.easeOut,
    );
    _speedPopupAnimation = CurvedAnimation(
      parent: _speedPopupController,
      curve: Curves.easeOut,
    );
  }

  void _initializePlayers() {
    _videoPlayer = Player();
    _videoController = VideoController(_videoPlayer);
    _audioPlayer = Player();
    _detectionPlayer = Player();
    _detectionVideoController = VideoController(_detectionPlayer);
    _detectionVideoController.player.setVolume(0.0);

    _videoPlayer.stream.playing.listen((isPlaying) {
      if (mounted) {
        if (_mode == PlaybackMode.adaptive) {
          if (isPlaying) {
            _audioPlayer.play();
          } else {
            _audioPlayer.pause();
          }
        }
        if (_isDetectionEnabled) {
          if (isPlaying) {
            _detectionPlayer.play();
          } else {
            _detectionPlayer.pause();
          }
        }
      }
    });

    _videoPlayer.stream.volume.listen((volume) {
      if (mounted) {
        setState(() {
          _currentVolume = volume;
        });
      }
    });
  }

  Future<void> _initializeDetector() async {
    try {
      await _detector.initialize();
      if (mounted) {
        setState(() {
          _isInitialized = true;
          _statusMessage = widget.videoJson != null 
              ? 'Ready!' 
              : 'Ready! Pick a video to start';
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => _statusMessage = 'Error: $e');
      }
    }
  }

  /// =====================
  /// STREAMING PLAYBACK
  /// =====================

  Player get _timelinePlayer {
    if (_mode == PlaybackMode.audioOnly) return _audioPlayer;
    return _videoPlayer;
  }

  Future<void> _openMuxed() async {
    _stopAudioSync();
    await _audioPlayer.stop();

    await _videoPlayer.open(Media(_videoStreams[_videoIndex].url));
    await _videoPlayer.play();
    
    // IMPORTANT: Also open in detection player for streaming mode
    await _detectionPlayer.open(Media(_videoStreams[_videoIndex].url));
    await _detectionPlayer.setVolume(0.0); // Keep it muted
    
    if (_isDetectionEnabled) {
      final aheadPos = _videoPlayer.state.position + 
          Duration(seconds: DETECTION_AHEAD_SECONDS);
      await _detectionPlayer.seek(aheadPos);
      await _detectionPlayer.play();
    } else {
      await _detectionPlayer.pause(); // Keep it paused if detection is off
    }
  }

  Future<void> _openAdaptive() async {
    _stopAudioSync();

    final video = _videoOnlyStreams[_videoIndex];
    final audio = _audioStreams[_audioIndex];

    await _videoPlayer.open(Media(video.url), play: false);
    await _audioPlayer.open(Media(audio.url), play: false);

    await _videoPlayer.seek(Duration.zero);
    await _audioPlayer.seek(Duration.zero);

    await _videoPlayer.play();
    await _audioPlayer.play();

    _startAudioSync();

    // IMPORTANT: Detection player must use the VIDEO-ONLY stream
    await _detectionPlayer.open(Media(video.url));
    await _detectionPlayer.setVolume(0.0);
    
    if (_isDetectionEnabled) {
      final aheadPos = Duration(seconds: DETECTION_AHEAD_SECONDS);
      await _detectionPlayer.seek(aheadPos);
      await _detectionPlayer.play();
    } else {
      await _detectionPlayer.pause();
    }
  }

  Future<void> _openAudioOnly() async {
    _stopAudioSync();
    await _videoPlayer.stop();
    await _detectionPlayer.stop(); // Stop detection in audio-only mode

    await _audioPlayer.open(Media(_audioStreams[_audioIndex].url));
    await _audioPlayer.play();
  }

  void _reload() {
    switch (_mode) {
      case PlaybackMode.muxed:
        _openMuxed();
        break;
      case PlaybackMode.adaptive:
        _openAdaptive();
        break;
      case PlaybackMode.audioOnly:
        _openAudioOnly();
        break;
    }
  }

  void _startAudioSync() {
    _audioSyncTimer?.cancel();

    _audioSyncTimer = Timer.periodic(
      const Duration(milliseconds: SYNC_INTERVAL_MS),
      (timer) {
        if (!mounted || _mode != PlaybackMode.adaptive) {
          timer.cancel();
          return;
        }

        final videoPos = _videoPlayer.state.position;
        final audioPos = _audioPlayer.state.position;
        final diffMs = (audioPos - videoPos).inMilliseconds;

        if (diffMs.abs() > 300) {
          _audioPlayer.seek(videoPos);
          _audioPlayer.setRate(1.0);
        } else if (diffMs.abs() > 80) {
          final correction = diffMs * -0.001;
          final rate = (1.0 + correction).clamp(0.95, 1.05);
          _audioPlayer.setRate(rate);
        } else {
          _audioPlayer.setRate(_currentSpeed);
        }
      },
    );
  }

  void _stopAudioSync() {
    _audioSyncTimer?.cancel();
    _audioSyncTimer = null;
    _audioPlayer.setRate(_currentSpeed);
  }

  /// =====================
  /// SUBTITLE HANDLING
  /// =====================

  Future<void> _loadSubtitle(String url, SubtitleType format) async {
    setState(() => _isLoadingSubtitle = true);

    try {
      if (url.isEmpty) {
        throw Exception('Empty subtitle URL');
      }

      final response = await http.get(
        Uri.parse(url),
        headers: {
          'User-Agent':
              'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        },
      ).timeout(const Duration(seconds: 10));

      if (response.statusCode != 200) {
        throw Exception('Failed to load subtitle: ${response.statusCode}');
      }

      final body = utf8.decode(response.bodyBytes);
      await _parseSubtitle(body, format);
      _currentSubtitleFormat = format;

      _startSubtitleSync();

      if (mounted) {
        setState(() => _isLoadingSubtitle = false);
      }
    } catch (e) {
      debugPrint('Failed to load subtitle: $e');
      _subtitleController = null;
      _currentSubtitleFormat = null;

      if (mounted) {
        setState(() {
          _currentSubtitle = '';
          _isLoadingSubtitle = false;
        });

        _showSnackbar('Failed to load subtitles: ${e.toString()}');
      }
    }
  }

  Future<void> _parseSubtitle(String content, SubtitleType format) async {
    try {
      String cleanedContent = content;
      if (format == SubtitleType.vtt) {
        cleanedContent = content
            .replaceAll(RegExp(r'<[\d:.,\s-]+>'), '')
            .replaceAll(RegExp(r'STYLE\s*\n.*?(?=\n\n|\Z)', dotAll: true), '');
      }

      final provider = SubtitleProvider.fromString(
        data: cleanedContent,
        type: format,
      );

      _subtitleController = SubtitleController(provider: provider);
      await _subtitleController!.initial();
    } catch (e) {
      debugPrint('Subtitle parsing error: $e');
      rethrow;
    }
  }

  void _startSubtitleSync() {
    _subtitleSyncSub?.cancel();

    final player = _timelinePlayer;

    _subtitleSyncSub = player.stream.position.listen((position) {
      if (_subtitleController == null) return;

      final subtitle = _subtitleController!.durationSearch(position);
      String newSubtitle = subtitle?.data ?? '';

      if (newSubtitle.isNotEmpty && _currentSubtitleFormat == SubtitleType.ttml) {
        newSubtitle = newSubtitle.parseHtmlString();
      }

      if (newSubtitle != _currentSubtitle) {
        setState(() => _currentSubtitle = newSubtitle);
      }
    });
  }

  void _stopSubtitleSync() {
    _subtitleSyncSub?.cancel();
    _subtitleSyncSub = null;
    _currentSubtitleFormat = null;
    setState(() => _currentSubtitle = '');
  }

  /// =====================
  /// UI CONTROL & KEYBOARD
  /// =====================

  void _showControlsTemporarily() {
    setState(() {
      _showControls = true;
    });
    _startHideTimer();
  }

  void _startHideTimer() {
    _hideControlsTimer?.cancel();
    _hideControlsTimer = Timer(CONTROLS_HIDE_DURATION, () {
      if (mounted &&
          _videoPlayer.state.playing &&
          !_isTimelineMode &&
          !_showVolumePopup &&
          !_showSpeedPopup &&
          !_showSettingsPopup) {
        setState(() {
          _showControls = false;
          _focusedControl = null;
        });
      }
    });
  }

  void _handleKeyPress(RawKeyEvent event) {
    if (event is RawKeyDownEvent) {
      _showControlsTemporarily();
      if (event.logicalKey == LogicalKeyboardKey.arrowUp) {
        _handleUpKey();
      } else if (event.logicalKey == LogicalKeyboardKey.arrowDown) {
        _handleDownKey();
      } else if (event.logicalKey == LogicalKeyboardKey.arrowLeft) {
        _handleLeftKey();
      } else if (event.logicalKey == LogicalKeyboardKey.arrowRight) {
        _handleRightKey();
      } else if (event.logicalKey == LogicalKeyboardKey.enter ||
          event.logicalKey == LogicalKeyboardKey.select) {
        _handleEnterKey();
      } else if (event.logicalKey == LogicalKeyboardKey.escape ||
          event.logicalKey == LogicalKeyboardKey.goBack) {
        _handleBackKey();
      }
    }
  }

  void _handleUpKey() {
    if (_showVolumePopup) {
      _adjustVolume(5);
    } else if (_showSpeedPopup) {
      _adjustSpeed(0.25);
    } else {
      setState(() {
        if (_isTimelineMode) {
          _isTimelineMode = false;
          _focusedControl = null;
        } else if (_focusedControl == null) {
          _isTimelineMode = true;
        } else {
          _isTimelineMode = true;
          _focusedControl = null;
        }
      });
    }
  }

  void _handleDownKey() {
    if (_showVolumePopup) {
      _adjustVolume(-5);
    } else if (_showSpeedPopup) {
      _adjustSpeed(-0.25);
    } else {
      setState(() {
        if (_isTimelineMode) {
          _isTimelineMode = false;
          _focusedControl = ControlButton.playPause;
        } else if (_focusedControl == null) {
          _focusedControl = ControlButton.playPause;
        }
      });
    }
  }

  void _handleLeftKey() {
    if (_showVolumePopup) {
      _adjustVolume(-5);
    } else if (_showSpeedPopup) {
      _adjustSpeed(-0.25);
    } else if (_isTimelineMode) {
      _seekBackward();
    } else {
      setState(() {
        if (_focusedControl == null) {
          _focusedControl = ControlButton.fullscreen;
        } else {
          final leftControls = [
            ControlButton.playPause,
            ControlButton.rewind,
            ControlButton.forward
          ];
          final rightControls = [
            ControlButton.detection,
            ControlButton.subtitle,
            ControlButton.volume,
            ControlButton.speed,
            ControlButton.settings,
            ControlButton.fullscreen
          ];

          if (leftControls.contains(_focusedControl)) {
            final currentIndex = leftControls.indexOf(_focusedControl!);
            if (currentIndex > 0) {
              _focusedControl = leftControls[currentIndex - 1];
            }
          } else if (rightControls.contains(_focusedControl)) {
            final currentIndex = rightControls.indexOf(_focusedControl!);
            if (currentIndex > 0) {
              _focusedControl = rightControls[currentIndex - 1];
            } else {
              _focusedControl = leftControls.last;
            }
          }
        }
      });
    }
  }

  void _handleRightKey() {
    if (_showVolumePopup) {
      _adjustVolume(5);
    } else if (_showSpeedPopup) {
      _adjustSpeed(0.25);
    } else if (_isTimelineMode) {
      _seekForward();
    } else {
      setState(() {
        if (_focusedControl == null) {
          _focusedControl = ControlButton.playPause;
        } else {
          final leftControls = [
            ControlButton.playPause,
            ControlButton.rewind,
            ControlButton.forward
          ];
          final rightControls = [
            ControlButton.detection,
            ControlButton.subtitle,
            ControlButton.volume,
            ControlButton.speed,
            ControlButton.settings,
            ControlButton.fullscreen
          ];

          if (leftControls.contains(_focusedControl)) {
            final currentIndex = leftControls.indexOf(_focusedControl!);
            if (currentIndex < leftControls.length - 1) {
              _focusedControl = leftControls[currentIndex + 1];
            } else {
              _focusedControl = rightControls.first;
            }
          } else if (rightControls.contains(_focusedControl)) {
            final currentIndex = rightControls.indexOf(_focusedControl!);
            if (currentIndex < rightControls.length - 1) {
              _focusedControl = rightControls[currentIndex + 1];
            }
          }
        }
      });
    }
  }

  void _handleEnterKey() {
    if (_showVolumePopup) {
      _hideVolumePopup();
    } else if (_showSpeedPopup) {
      _hideSpeedPopup();
    } else if (_showSettingsPopup) {
      setState(() => _showSettingsPopup = false);
    } else if (_isTimelineMode) {
      setState(() {
        _isTimelineMode = false;
      });
    } else if (_focusedControl != null) {
      _executeControlAction(_focusedControl!);
    } else {
      _togglePlayPause();
    }
  }

  void _handleBackKey() {
    if (_showVolumePopup) {
      _hideVolumePopup();
    } else if (_showSpeedPopup) {
      _hideSpeedPopup();
    } else if (_showSettingsPopup) {
      setState(() => _showSettingsPopup = false);
    } else if (_isTimelineMode) {
      setState(() {
        _isTimelineMode = false;
      });
    } else if (_isFullscreen) {
      _toggleFullscreen();
    }
  }

  void _executeControlAction(ControlButton control) {
    switch (control) {
      case ControlButton.playPause:
        _togglePlayPause();
        break;
      case ControlButton.rewind:
        _seekBackward(seconds: 10);
        break;
      case ControlButton.forward:
        _seekForward(seconds: 10);
        break;
      case ControlButton.volume:
        _showVolumePopupDialog();
        break;
      case ControlButton.speed:
        _showSpeedPopupDialog();
        break;
      case ControlButton.settings:
        setState(() => _showSettingsPopup = !_showSettingsPopup);
        break;
      case ControlButton.fullscreen:
        _toggleFullscreen();
        break;
      case ControlButton.detection:
        _toggleDetection();
        break;
      case ControlButton.subtitle:
        _toggleSubtitle();
        break;
      default:
        break;
    }
  }

  void _toggleSubtitle() {
    if (_subtitleTracks.isEmpty) {
      _showSnackbar('No subtitles available');
      return;
    }

    if (_subtitleIndex == -1) {
      // Turn on first subtitle
      setState(() => _subtitleIndex = 0);
      _loadSubtitle(_subtitleTracks[0].url, _subtitleTracks[0].format);
    } else {
      // Turn off
      setState(() => _subtitleIndex = -1);
      _stopSubtitleSync();
      _subtitleController = null;
    }
  }

  void _showVolumePopupDialog() {
    setState(() {
      _showVolumePopup = true;
      _showSpeedPopup = false;
    });
    _volumePopupController.forward();
    _speedPopupController.reverse();
  }

  void _hideVolumePopup() {
    _volumePopupController.reverse().then((_) {
      if (mounted) {
        setState(() {
          _showVolumePopup = false;
        });
      }
    });
  }

  void _showSpeedPopupDialog() {
    setState(() {
      _showSpeedPopup = true;
      _showVolumePopup = false;
    });
    _speedPopupController.forward();
    _volumePopupController.reverse();
  }

  void _hideSpeedPopup() {
    _speedPopupController.reverse().then((_) {
      if (mounted) {
        setState(() {
          _showSpeedPopup = false;
        });
      }
    });
  }

  void _adjustVolume(double delta) {
    final newVolume = (_currentVolume + delta).clamp(0.0, 100.0);
    setState(() {
      _currentVolume = newVolume;
    });
    _videoPlayer.setVolume(newVolume);
    if (_mode != PlaybackMode.audioOnly) {
      _audioPlayer.setVolume(newVolume);
    }
  }

  void _adjustSpeed(double delta) {
    final newSpeed = (_currentSpeed + delta).clamp(0.25, 2.0);
    setState(() {
      _currentSpeed = newSpeed;
    });
    _videoPlayer.setRate(newSpeed);
    if (_mode == PlaybackMode.adaptive) _audioPlayer.setRate(newSpeed);
    if (_isDetectionEnabled) _detectionPlayer.setRate(newSpeed);
  }

  void _togglePlayPause() {
    if (_videoPlayer.state.playing) {
      _videoPlayer.pause();
      if (_mode == PlaybackMode.adaptive) _audioPlayer.pause();
      if (_isDetectionEnabled) _detectionPlayer.pause();
    } else {
      _videoPlayer.play();
      if (_mode == PlaybackMode.adaptive) _audioPlayer.play();
      if (_isDetectionEnabled) _detectionPlayer.play();
    }
  }

  void _seekForward({int seconds = 5}) {
    final currentPos = _timelinePlayer.state.position;
    final duration = _timelinePlayer.state.duration ?? Duration.zero;
    final newPos = (currentPos + Duration(seconds: seconds));
    if (newPos <= duration) {
      _videoPlayer.seek(newPos);
      if (_mode == PlaybackMode.adaptive) _audioPlayer.seek(newPos);
      if (_isDetectionEnabled) {
        final aheadPos = newPos + Duration(seconds: DETECTION_AHEAD_SECONDS);
        _detectionPlayer.seek(aheadPos);
        _detectionCache.clear();
      }
    }
  }

  void _seekBackward({int seconds = 5}) {
    final currentPos = _timelinePlayer.state.position;
    final newPos = currentPos - Duration(seconds: seconds);
    if (newPos >= Duration.zero) {
      _videoPlayer.seek(newPos);
      if (_mode == PlaybackMode.adaptive) _audioPlayer.seek(newPos);
      if (_isDetectionEnabled) {
        final aheadPos = newPos + Duration(seconds: DETECTION_AHEAD_SECONDS);
        _detectionPlayer.seek(aheadPos);
        _detectionCache.clear();
      }
    }
  }

  void _toggleFullscreen() {
    setState(() {
      _isFullscreen = !_isFullscreen;
    });
    if (_isFullscreen) {
      SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky);
      SystemChrome.setPreferredOrientations([
        DeviceOrientation.landscapeLeft,
        DeviceOrientation.landscapeRight,
      ]);
    } else {
      SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
      SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
        DeviceOrientation.landscapeLeft,
        DeviceOrientation.landscapeRight,
      ]);
    }
  }

  Future<void> _pickVideo() async {
    try {
      final result = await FilePicker.platform.pickFiles(
        type: FileType.video,
        allowMultiple: false,
      );

      if (result != null && result.files.single.path != null) {
        final path = result.files.single.path!;
        _currentVideoPath = path;

        await _videoPlayer.open(Media(path));
        await _detectionPlayer.open(Media(path));
        await _detectionPlayer.setVolume(0.0); // Keep detection player muted
        
        await _videoPlayer.setRate(1.0);
        await _detectionPlayer.setRate(1.0);
        await _videoPlayer.play();

        if (mounted) {
          setState(() {
            _statusMessage = 'Video loaded';
          });
        }
      }
    } catch (e) {
      _showSnackbar('Error loading video: $e');
    }
  }

  /// =====================
  /// DETECTION LOGIC
  /// =====================

  void _toggleDetection() {
    if (!_isInitialized || (_currentVideoPath == null && widget.videoJson == null)) {
      _showSnackbar('Please load a video first');
      return;
    }

    if (_isDetectionEnabled) {
      _stopDetection();
    } else {
      _startDetection();
    }
  }

  void _startDetection() async {
    if (_mode == PlaybackMode.audioOnly) {
      _showSnackbar('Detection not available in audio-only mode');
      return;
    }

    setState(() {
      _isDetectionEnabled = true;
      _frameCount = 0;
      _fpsHistory.clear();
      _detectionCache.clear();
      _lastLookupKey = -1;
      _syncDriftMs = 0;
      _statusMessage = 'Detection active';
    });

    final mainPosition = _videoPlayer.state.position;
    final videoDuration = _videoPlayer.state.duration ?? Duration.zero;
    final aheadMs = (mainPosition.inMilliseconds + DETECTION_AHEAD_SECONDS * 1000)
        .clamp(0, videoDuration.inMilliseconds);
    final aheadPosition = Duration(milliseconds: aheadMs);

    // Make sure detection player is playing
    await _detectionPlayer.play();
    await _detectionPlayer.seek(aheadPosition);
    await Future.delayed(const Duration(milliseconds: 300));

    _captureTimer = Timer.periodic(
      const Duration(milliseconds: CAPTURE_INTERVAL_MS),
      (timer) {
        if (!mounted || !_isDetectionEnabled) {
          timer.cancel();
          return;
        }

        if (!_isProcessing && _detectionPlayer.state.playing) {
          _captureAndDetect();
        }
      },
    );

    _syncTimer = Timer.periodic(
      const Duration(milliseconds: SYNC_INTERVAL_MS),
      (timer) {
        if (!mounted || !_isDetectionEnabled) {
          timer.cancel();
          return;
        }

        _syncDetections();
      },
    );

    _syncCheckTimer = Timer.periodic(
      const Duration(milliseconds: SYNC_CHECK_INTERVAL_MS),
      (timer) {
        if (!mounted || !_isDetectionEnabled) {
          timer.cancel();
          return;
        }

        _checkAndCorrectSync();
      },
    );
  }

  void _stopDetection() {
    _captureTimer?.cancel();
    _syncTimer?.cancel();
    _syncCheckTimer?.cancel();
    _detectionPlayer.pause();

    setState(() {
      _isDetectionEnabled = false;
      _currentDetections = [];
      _detectionCache.clear();
      _objectCount = 0;
      _fps = 0.0;
      _frameCount = 0;
      _fpsHistory.clear();
      _lastLookupKey = -1;
      _syncDriftMs = 0;
      _statusMessage = 'Detection stopped';
    });
  }

  void _checkAndCorrectSync() async {
    if (!_isDetectionEnabled || !mounted) return;

    final mainPos = _videoPlayer.state.position.inMilliseconds;
    final detectionPos = _detectionPlayer.state.position.inMilliseconds;
    final expectedDetectionPos = mainPos + (DETECTION_AHEAD_SECONDS * 1000);
    final actualDrift = (detectionPos - expectedDetectionPos).abs();

    if (mounted) {
      setState(() {
        _syncDriftMs = actualDrift;
      });
    }

    if (actualDrift > MAX_DRIFT_MS) {
      final videoDuration = _videoPlayer.state.duration ?? Duration.zero;
      final correctedPos = Duration(
          milliseconds: (mainPos + DETECTION_AHEAD_SECONDS * 1000)
              .clamp(0, videoDuration.inMilliseconds));
      await _detectionPlayer.seek(correctedPos);
    }
  }

  Future<void> _captureAndDetect() async {
    if (_isProcessing || !mounted) return;

    _isProcessing = true;

    try {
      final startTime = DateTime.now();
      final detectionPosition = _detectionPlayer.state.position;
      final timestampMs = detectionPosition.inMilliseconds;
      final timestampKey = (timestampMs / 25).round();

      if (_detectionCache.containsKey(timestampKey)) {
        _isProcessing = false;
        return;
      }

      final frameBytes = await _detectionPlayer.screenshot(format: 'image/jpeg');

      if (frameBytes == null || !mounted) {
        _isProcessing = false;
        return;
      }

      final detections = await _detector.detectObjects(
        frameBytes,
        confidenceThreshold: 0.38,
      );

      if (!mounted) {
        _isProcessing = false;
        return;
      }

      _detectionCache[timestampKey] = detections;

      final mainPosition = _videoPlayer.state.position;
      final mainKey = (mainPosition.inMilliseconds / 25).round();

      if (_detectionCache.length > CACHE_CLEANUP_THRESHOLD) {
        _detectionCache.removeWhere((key, value) => key < mainKey - 80);
      }

      final duration = DateTime.now().difference(startTime).inMilliseconds;
      final fps = duration > 0 ? 1000.0 / duration : 0.0;

      _fpsHistory.add(fps);
      if (_fpsHistory.length > 30) _fpsHistory.removeAt(0);

      _frameCount++;

      final now = DateTime.now();
      if (_lastFpsUpdate == null ||
          now.difference(_lastFpsUpdate!).inMilliseconds > 500) {
        if (mounted && _fpsHistory.isNotEmpty) {
          final avgFps = _fpsHistory.reduce((a, b) => a + b) / _fpsHistory.length;
          _fps = avgFps;
        }

        _lastFpsUpdate = now;
      }
    } catch (e) {
      print('[Detection] Error: $e');
    } finally {
      _isProcessing = false;
    }
  }

  void _syncDetections() {
    if (!mounted || !_isDetectionEnabled) return;

    final mainPosition = _videoPlayer.state.position;
    final mainMs = mainPosition.inMilliseconds;
    final timestampKey = (mainMs / 25).round();

    if (timestampKey == _lastLookupKey) return;

    _lastLookupKey = timestampKey;

    List<DetectionResult>? detections;

    if (_detectionCache.containsKey(timestampKey)) {
      detections = _detectionCache[timestampKey]!;
    } else {
      for (int offset = -8; offset <= 8; offset++) {
        final nearbyKey = timestampKey + offset;
        if (_detectionCache.containsKey(nearbyKey)) {
          detections = _detectionCache[nearbyKey]!;
          break;
        }
      }
    }

    if (detections != null) {
      if (_currentDetections.length != detections.length ||
          (_currentDetections.isEmpty && detections.isNotEmpty)) {
        setState(() {
          _currentDetections = detections!;
          _objectCount = detections.length;
        });
      }
    }
  }

  void _showSnackbar(String message) {
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(message), duration: const Duration(seconds: 2)),
      );
    }
  }

  /// =====================
  /// BUILD UI
  /// =====================

  @override
  Widget build(BuildContext context) {
    return RawKeyboardListener(
      focusNode: _mainFocusNode,
      onKey: _handleKeyPress,
      autofocus: true,
      child: Scaffold(
        backgroundColor: Colors.black,
        body: Stack(
          children: [
            _buildVideoPlayerContent(),
            if (_showControls && (_currentVideoPath != null || widget.videoJson != null))
              Positioned(
                left: 0,
                right: 0,
                bottom: 0,
                child: _buildYouTubeTVControls(),
              ),
            if (_currentVideoPath == null && widget.videoJson == null)
              Center(
                child: ElevatedButton.icon(
                  onPressed: _pickVideo,
                  icon: const Icon(Icons.video_library, size: 32),
                  label: const Text('Pick Video', style: TextStyle(fontSize: 18)),
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                    backgroundColor: Colors.deepPurple,
                    foregroundColor: Colors.white,
                  ),
                ),
              ),
            // Subtitle overlay
            if (_currentSubtitle.isNotEmpty && _mode != PlaybackMode.audioOnly)
              _buildSubtitleOverlay(),
            // Loading indicator for subtitles
            if (_isLoadingSubtitle)
              Positioned(
                top: 50,
                right: 20,
                child: Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.7),
                    borderRadius: BorderRadius.circular(4),
                  ),
                  child: const Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      SizedBox(
                        width: 16,
                        height: 16,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          color: Colors.white,
                        ),
                      ),
                      SizedBox(width: 8),
                      Text(
                        'Loading subtitles...',
                        style: TextStyle(color: Colors.white, fontSize: 12),
                      ),
                    ],
                  ),
                ),
              ),
            // Volume popup
            if (_showVolumePopup)
              Positioned(
                right: 100,
                bottom: 120,
                child: _buildVolumePopup(),
              ),
            // Speed popup
            if (_showSpeedPopup)
              Positioned(
                right: 180,
                bottom: 120,
                child: _buildSpeedPopup(),
              ),
            // Settings popup
            if (_showSettingsPopup)
              Positioned(
                right: 20,
                bottom: 120,
                child: _buildSettingsPopup(),
              ),
          ],
        ),
      ),
    );
  }

  Widget _buildSubtitleOverlay() {
    double? top, bottom;

    switch (_subtitleConfig.position) {
      case SubtitlePosition.top:
        top = 60;
        break;
      case SubtitlePosition.center:
        top = null;
        bottom = null;
        break;
      case SubtitlePosition.bottom:
        bottom = 120;
        break;
    }

    return Positioned(
      left: 16,
      right: 16,
      top: top,
      bottom: bottom,
      child: Center(
        child: Container(
          padding: _subtitleConfig.padding,
          decoration: BoxDecoration(
            color: _subtitleConfig.backgroundColor
                .withOpacity(_subtitleConfig.backgroundOpacity),
            borderRadius: BorderRadius.circular(4),
          ),
          child: Text(
            _currentSubtitle,
            textAlign: TextAlign.center,
            style: TextStyle(
              color: _subtitleConfig.textColor,
              fontSize: _subtitleConfig.fontSize,
              fontWeight: _subtitleConfig.fontWeight,
              height: 1.4,
              shadows: _subtitleConfig.hasShadow
                  ? const [
                      Shadow(
                        offset: Offset(1, 1),
                        blurRadius: 3,
                        color: Colors.black,
                      ),
                    ]
                  : null,
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSettingsPopup() {
    return Container(
      width: 350,
      constraints: BoxConstraints(maxHeight: MediaQuery.of(context).size.height * 0.7),
      decoration: BoxDecoration(
        color: Colors.black.withOpacity(0.95),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.white.withOpacity(0.3), width: 2),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.5),
            blurRadius: 20,
            spreadRadius: 5,
          ),
        ],
      ),
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text(
                  'Settings',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.close, color: Colors.white),
                  onPressed: () => setState(() => _showSettingsPopup = false),
                ),
              ],
            ),
            const Divider(color: Colors.white24),
            
            // Playback Mode
            if (widget.videoJson != null && _videoOnlyStreams.isNotEmpty) ...[
              const SizedBox(height: 12),
              const Text(
                'Playback Mode',
                style: TextStyle(color: Colors.white70, fontSize: 14),
              ),
              const SizedBox(height: 8),
              ...PlaybackMode.values.map((mode) {
                final isSelected = _mode == mode;
                return InkWell(
                  onTap: () {
                    setState(() => _mode = mode);
                    _reload();
                  },
                  child: Container(
                    padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    margin: const EdgeInsets.only(bottom: 4),
                    decoration: BoxDecoration(
                      color: isSelected
                          ? Colors.white.withOpacity(0.2)
                          : Colors.transparent,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          mode.name.toUpperCase(),
                          style: TextStyle(
                            color: isSelected ? Colors.white : Colors.white70,
                            fontWeight:
                                isSelected ? FontWeight.bold : FontWeight.normal,
                          ),
                        ),
                        if (isSelected)
                          const Icon(Icons.check, color: Colors.white, size: 18),
                      ],
                    ),
                  ),
                );
              }).toList(),
            ],
            
            // Video Quality
            if (_mode != PlaybackMode.audioOnly) ...[
              const SizedBox(height: 16),
              const Divider(color: Colors.white24),
              const SizedBox(height: 12),
              const Text(
                'Video Quality',
                style: TextStyle(color: Colors.white70, fontSize: 14),
              ),
              const SizedBox(height: 8),
              ...List.generate(
                _mode == PlaybackMode.muxed
                    ? _videoStreams.length
                    : _videoOnlyStreams.length,
                (i) {
                  final stream = _mode == PlaybackMode.muxed
                      ? _videoStreams[i]
                      : _videoOnlyStreams[i];
                  final isSelected = _videoIndex == i;
                  return InkWell(
                    onTap: () {
                      setState(() => _videoIndex = i);
                      _reload();
                    },
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                          vertical: 12, horizontal: 16),
                      margin: const EdgeInsets.only(bottom: 4),
                      decoration: BoxDecoration(
                        color: isSelected
                            ? Colors.white.withOpacity(0.2)
                            : Colors.transparent,
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            stream.resolution,
                            style: TextStyle(
                              color: isSelected ? Colors.white : Colors.white70,
                              fontWeight:
                                  isSelected ? FontWeight.bold : FontWeight.normal,
                            ),
                          ),
                          if (isSelected)
                            const Icon(Icons.check, color: Colors.white, size: 18),
                        ],
                      ),
                    ),
                  );
                },
              ),
            ],
            
            // Audio Track
            if (_audioStreams.isNotEmpty) ...[
              const SizedBox(height: 16),
              const Divider(color: Colors.white24),
              const SizedBox(height: 12),
              const Text(
                'Audio Track',
                style: TextStyle(color: Colors.white70, fontSize: 14),
              ),
              const SizedBox(height: 8),
              ...List.generate(_audioStreams.length, (i) {
                final audio = _audioStreams[i];
                final isSelected = _audioIndex == i;
                return InkWell(
                  onTap: () {
                    setState(() => _audioIndex = i);
                    _reload();
                  },
                  child: Container(
                    padding:
                        const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    margin: const EdgeInsets.only(bottom: 4),
                    decoration: BoxDecoration(
                      color: isSelected
                          ? Colors.white.withOpacity(0.2)
                          : Colors.transparent,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          audio.language ?? 'Audio $i',
                          style: TextStyle(
                            color: isSelected ? Colors.white : Colors.white70,
                            fontWeight:
                                isSelected ? FontWeight.bold : FontWeight.normal,
                          ),
                        ),
                        if (isSelected)
                          const Icon(Icons.check, color: Colors.white, size: 18),
                      ],
                    ),
                  ),
                );
              }),
            ],
            
            // Subtitles
            if (_subtitleTracks.isNotEmpty) ...[
              const SizedBox(height: 16),
              const Divider(color: Colors.white24),
              const SizedBox(height: 12),
              const Text(
                'Subtitles',
                style: TextStyle(color: Colors.white70, fontSize: 14),
              ),
              const SizedBox(height: 8),
              InkWell(
                onTap: () {
                  setState(() => _subtitleIndex = -1);
                  _stopSubtitleSync();
                  _subtitleController = null;
                },
                child: Container(
                  padding:
                      const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                  margin: const EdgeInsets.only(bottom: 4),
                  decoration: BoxDecoration(
                    color: _subtitleIndex == -1
                        ? Colors.white.withOpacity(0.2)
                        : Colors.transparent,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Off',
                        style: TextStyle(
                          color:
                              _subtitleIndex == -1 ? Colors.white : Colors.white70,
                          fontWeight: _subtitleIndex == -1
                              ? FontWeight.bold
                              : FontWeight.normal,
                        ),
                      ),
                      if (_subtitleIndex == -1)
                        const Icon(Icons.check, color: Colors.white, size: 18),
                    ],
                  ),
                ),
              ),
              ...List.generate(_subtitleTracks.length, (i) {
                final sub = _subtitleTracks[i];
                final isSelected = _subtitleIndex == i;
                return InkWell(
                  onTap: () async {
                    setState(() => _subtitleIndex = i);
                    await _loadSubtitle(sub.url, sub.format);
                  },
                  child: Container(
                    padding:
                        const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    margin: const EdgeInsets.only(bottom: 4),
                    decoration: BoxDecoration(
                      color: isSelected
                          ? Colors.white.withOpacity(0.2)
                          : Colors.transparent,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Expanded(
                          child: Text(
                            sub.label,
                            style: TextStyle(
                              color: isSelected ? Colors.white : Colors.white70,
                              fontWeight:
                                  isSelected ? FontWeight.bold : FontWeight.normal,
                            ),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                        if (isSelected)
                          const Icon(Icons.check, color: Colors.white, size: 18),
                      ],
                    ),
                  ),
                );
              }),
              
              // Subtitle customization
              if (_subtitleIndex != -1) ...[
                const SizedBox(height: 16),
                const Divider(color: Colors.white24),
                const SizedBox(height: 12),
                Text(
                  'Font Size: ${_subtitleConfig.fontSize.toInt()}',
                  style: const TextStyle(color: Colors.white70, fontSize: 14),
                ),
                Slider(
                  value: _subtitleConfig.fontSize,
                  min: 12,
                  max: 36,
                  divisions: 24,
                  onChanged: (value) {
                    setState(() {
                      _subtitleConfig = _subtitleConfig.copyWith(fontSize: value);
                    });
                  },
                ),
                const SizedBox(height: 12),
                const Text(
                  'Position',
                  style: TextStyle(color: Colors.white70, fontSize: 14),
                ),
                const SizedBox(height: 8),
                ...SubtitlePosition.values.map((pos) {
                  final isSelected = _subtitleConfig.position == pos;
                  return InkWell(
                    onTap: () {
                      setState(() {
                        _subtitleConfig =
                            _subtitleConfig.copyWith(position: pos);
                      });
                    },
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                          vertical: 12, horizontal: 16),
                      margin: const EdgeInsets.only(bottom: 4),
                      decoration: BoxDecoration(
                        color: isSelected
                            ? Colors.white.withOpacity(0.2)
                            : Colors.transparent,
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            pos.name.toUpperCase(),
                            style: TextStyle(
                              color: isSelected ? Colors.white : Colors.white70,
                              fontWeight:
                                  isSelected ? FontWeight.bold : FontWeight.normal,
                            ),
                          ),
                          if (isSelected)
                            const Icon(Icons.check, color: Colors.white, size: 18),
                        ],
                      ),
                    ),
                  );
                }).toList(),
                const SizedBox(height: 12),
                const Text(
                  'Text Color',
                  style: TextStyle(color: Colors.white70, fontSize: 14),
                ),
                const SizedBox(height: 8),
                Wrap(
                  spacing: 10,
                  children: [
                    Colors.white,
                    Colors.yellow,
                    Colors.cyan,
                    Colors.green,
                    Colors.red,
                  ].map((color) {
                    return GestureDetector(
                      onTap: () {
                        setState(() {
                          _subtitleConfig =
                              _subtitleConfig.copyWith(textColor: color);
                        });
                      },
                      child: Container(
                        width: 40,
                        height: 40,
                        decoration: BoxDecoration(
                          color: color,
                          shape: BoxShape.circle,
                          border: Border.all(
                            color: _subtitleConfig.textColor == color
                                ? Colors.blue
                                : Colors.grey,
                            width: 3,
                          ),
                        ),
                      ),
                    );
                  }).toList(),
                ),
              ],
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildVolumePopup() {
    return ScaleTransition(
      scale: _volumePopupAnimation,
      child: FadeTransition(
        opacity: _volumePopupAnimation,
        child: Container(
          width: 60,
          height: 200,
          decoration: BoxDecoration(
            color: Colors.black.withOpacity(0.9),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: Colors.white.withOpacity(0.3), width: 2),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.5),
                blurRadius: 20,
                spreadRadius: 5,
              ),
            ],
          ),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(
                _currentVolume > 50
                    ? Icons.volume_up
                    : _currentVolume > 0
                        ? Icons.volume_down
                        : Icons.volume_off,
                color: Colors.white,
                size: 24,
              ),
              const SizedBox(height: 12),
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  child: RotatedBox(
                    quarterTurns: 3,
                    child: SliderTheme(
                      data: SliderThemeData(
                        trackHeight: 4,
                        thumbShape:
                            const RoundSliderThumbShape(enabledThumbRadius: 8),
                        overlayShape:
                            const RoundSliderOverlayShape(overlayRadius: 16),
                        activeTrackColor: Colors.white,
                        inactiveTrackColor: Colors.white.withOpacity(0.3),
                        thumbColor: Colors.white,
                      ),
                      child: Slider(
                        value: _currentVolume,
                        min: 0,
                        max: 100,
                        onChanged: (value) {
                          setState(() {
                            _currentVolume = value;
                          });
                          _videoPlayer.setVolume(value);
                          if (_mode == PlaybackMode.adaptive) {
                            _audioPlayer.setVolume(value);
                          }
                        },
                      ),
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 8),
              Text(
                '${_currentVolume.round()}%',
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 14,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 8),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSpeedPopup() {
    final speeds = [0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0];
    return ScaleTransition(
      scale: _speedPopupAnimation,
      child: FadeTransition(
        opacity: _speedPopupAnimation,
        child: Container(
          width: 120,
          decoration: BoxDecoration(
            color: Colors.black.withOpacity(0.9),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: Colors.white.withOpacity(0.3), width: 2),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.5),
                blurRadius: 20,
                spreadRadius: 5,
              ),
            ],
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Padding(
                padding: EdgeInsets.all(12),
                child: Row(
                  children: [
                    Icon(Icons.speed, color: Colors.white, size: 20),
                    SizedBox(width: 8),
                    Text(
                      'Speed',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 14,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
              ),
              const Divider(color: Colors.white24, height: 1),
              ...speeds.map((speed) {
                final isSelected = (_currentSpeed - speed).abs() < 0.01;
                return InkWell(
                  onTap: () {
                    _adjustSpeed(speed - _currentSpeed);
                  },
                  child: Container(
                    padding:
                        const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
                    color: isSelected
                        ? Colors.white.withOpacity(0.2)
                        : Colors.transparent,
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          '${speed}x',
                          style: TextStyle(
                            color: isSelected ? Colors.white : Colors.white70,
                            fontSize: 14,
                            fontWeight:
                                isSelected ? FontWeight.bold : FontWeight.normal,
                          ),
                        ),
                        if (isSelected)
                          const Icon(Icons.check, color: Colors.white, size: 16),
                      ],
                    ),
                  ),
                );
              }).toList(),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildVideoPlayerContent() {
    if (_mode == PlaybackMode.audioOnly) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.music_note,
              size: 80,
              color: Colors.white.withOpacity(0.5),
            ),
            const SizedBox(height: 16),
            Text(
              'Audio Only Mode',
              style: TextStyle(
                color: Colors.white.withOpacity(0.7),
                fontSize: 20,
              ),
            ),
          ],
        ),
      );
    }

    return Center(
      child: AspectRatio(
        aspectRatio: 16 / 9,
        child: Container(
          color: Colors.black,
          child: LayoutBuilder(
            builder: (context, constraints) {
              return StreamBuilder(
                stream: _videoPlayer.stream.width,
                builder: (context, widthSnapshot) {
                  return StreamBuilder(
                    stream: _videoPlayer.stream.height,
                    builder: (context, heightSnapshot) {
                      final videoWidth = widthSnapshot.data ?? 1920;
                      final videoHeight = heightSnapshot.data ?? 1080;

                      return Stack(
                        children: [
                          Video(
                            controller: _videoController,
                            controls: NoVideoControls,
                          ),
                          if (_isDetectionEnabled &&
                              _currentDetections.isNotEmpty &&
                              videoWidth > 0 &&
                              videoHeight > 0)
                            _buildDetectionOverlay(
                              constraints,
                              videoWidth.toDouble(),
                              videoHeight.toDouble(),
                            ),
                          Positioned(
                            left: -10000,
                            top: -10000,
                            width: 1,
                            height: 1,
                            child: Video(
                              controller: _detectionVideoController,
                              controls: NoVideoControls,
                            ),
                          ),
                        ],
                      );
                    },
                  );
                },
              );
            },
          ),
        ),
      ),
    );
  }

  Widget _buildYouTubeTVControls() {
    return Container(
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: [
            Colors.transparent,
            Colors.black.withOpacity(0.85),
          ],
        ),
      ),
      child: SafeArea(
        child: Padding(
          padding: const EdgeInsets.fromLTRB(24, 16, 24, 20),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              // Timeline
              StreamBuilder(
                stream: _timelinePlayer.stream.position,
                builder: (context, snapshot) {
                  final position = snapshot.data ?? Duration.zero;
                  final duration = _timelinePlayer.state.duration ?? Duration.zero;

                  return Column(
                    children: [
                      // Progress bar
                      GestureDetector(
                        onTapDown: (details) {
                          final dx = details.localPosition.dx;
                          final width = context.size!.width - 48;
                          final ratio = (dx / width).clamp(0.0, 1.0);
                          final newPos = Duration(
                            milliseconds:
                                (ratio * duration.inMilliseconds).toInt(),
                          );

                          _videoPlayer.seek(newPos);
                          if (_mode == PlaybackMode.adaptive) {
                            _audioPlayer.seek(newPos);
                          }
                          if (_isDetectionEnabled) {
                            final aheadPos = Duration(
                              milliseconds: (newPos.inMilliseconds +
                                      DETECTION_AHEAD_SECONDS * 1000)
                                  .clamp(0, duration.inMilliseconds),
                            );
                            _detectionPlayer.seek(aheadPos);
                            _detectionCache.clear();
                          }
                        },
                        child: Container(
                          height: 8,
                          decoration: _isTimelineMode
                              ? BoxDecoration(
                                  border: Border.all(
                                    color: Colors.white,
                                    width: 2,
                                  ),
                                  borderRadius: BorderRadius.circular(6),
                                  boxShadow: [
                                    BoxShadow(
                                      color: Colors.white.withOpacity(0.5),
                                      blurRadius: 10,
                                      spreadRadius: 2,
                                    ),
                                  ],
                                )
                              : null,
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(4),
                            child: Stack(
                              children: [
                                Container(
                                  color: Colors.white.withOpacity(0.3),
                                ),
                                FractionallySizedBox(
                                  widthFactor: duration.inMilliseconds > 0
                                      ? (position.inMilliseconds /
                                              duration.inMilliseconds)
                                          .clamp(0.0, 1.0)
                                      : 0.0,
                                  alignment: Alignment.centerLeft,
                                  child: Container(
                                    decoration: BoxDecoration(
                                      color: Theme.of(context).colorScheme.primary,
                                      boxShadow: [
                                        BoxShadow(
                                          color: Theme.of(context).colorScheme.primary.withOpacity(0.5),
                                          blurRadius: 4,
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(height: 10),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            _formatDuration(position),
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontWeight: FontWeight.w500,
                            ),
                          ),
                          Text(
                            _formatDuration(duration),
                            style: TextStyle(
                              color: Colors.white.withOpacity(0.7),
                              fontSize: 13,
                            ),
                          ),
                        ],
                      ),
                    ],
                  );
                },
              ),
              const SizedBox(height: 20),
              // Control buttons
              Row(
                children: [
                  // LEFT GROUP
                  _buildTVControlButton(
                    icon: _videoPlayer.state.playing
                        ? Icons.pause
                        : Icons.play_arrow,
                    control: ControlButton.playPause,
                    size: 56,
                    iconSize: 36,
                  ),
                  const SizedBox(width: 12),
                  _buildTVControlButton(
                    icon: Icons.replay_10,
                    control: ControlButton.rewind,
                  ),
                  const SizedBox(width: 12),
                  _buildTVControlButton(
                    icon: Icons.forward_10,
                    control: ControlButton.forward,
                  ),
                  const Spacer(),
                  // RIGHT GROUP
                  _buildTVControlButton(
                    icon: _isDetectionEnabled ? Icons.radar : Icons.radar_outlined,
                    control: ControlButton.detection,
                    isActive: _isDetectionEnabled,
                  ),
                  const SizedBox(width: 12),
                  if (_subtitleTracks.isNotEmpty) ...[
                    _buildTVControlButton(
                      icon: Icons.closed_caption,
                      control: ControlButton.subtitle,
                      isActive: _subtitleIndex != -1,
                    ),
                    const SizedBox(width: 12),
                  ],
                  _buildTVControlButton(
                    icon: _currentVolume > 50
                        ? Icons.volume_up
                        : _currentVolume > 0
                            ? Icons.volume_down
                            : Icons.volume_off,
                    control: ControlButton.volume,
                  ),
                  const SizedBox(width: 12),
                  _buildTVControlButton(
                    icon: Icons.speed,
                    control: ControlButton.speed,
                    label: '${_currentSpeed}x',
                  ),
                  const SizedBox(width: 12),
                  _buildTVControlButton(
                    icon: Icons.settings,
                    control: ControlButton.settings,
                    isActive: _showSettingsPopup,
                  ),
                  const SizedBox(width: 12),
                  _buildTVControlButton(
                    icon: _isFullscreen
                        ? Icons.fullscreen_exit
                        : Icons.fullscreen,
                    control: ControlButton.fullscreen,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTVControlButton({
    required IconData icon,
    required ControlButton control,
    double size = 48,
    double iconSize = 26,
    String? label,
    bool isActive = false,
  }) {
    final isFocused = _focusedControl == control;
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        color: isActive
            ? Colors.green.withOpacity(0.3)
            : Colors.white.withOpacity(isFocused ? 0.3 : 0.15),
        borderRadius: BorderRadius.circular(size / 2),
        border: Border.all(
          color: isFocused ? Colors.white : Colors.transparent,
          width: 3,
        ),
        boxShadow: isFocused
            ? [
                BoxShadow(
                  color: Colors.white.withOpacity(0.6),
                  blurRadius: 15,
                  spreadRadius: 3,
                ),
              ]
            : [],
      ),
      child: Center(
        child: label != null
            ? Text(
                label,
                style: TextStyle(
                  color: Colors.white,
                  fontSize: iconSize * 0.4,
                  fontWeight: FontWeight.bold,
                ),
              )
            : Icon(
                icon,
                color: isActive ? Colors.greenAccent : Colors.white,
                size: iconSize,
              ),
      ),
    );
  }

  Widget _buildDetectionOverlay(
    BoxConstraints constraints,
    double videoWidth,
    double videoHeight,
  ) {
    final videoAspectRatio = videoWidth / videoHeight;
    final containerAspectRatio = constraints.maxWidth / constraints.maxHeight;

    double displayWidth;
    double displayHeight;
    double offsetX = 0;
    double offsetY = 0;

    if (containerAspectRatio > videoAspectRatio) {
      displayHeight = constraints.maxHeight;
      displayWidth = displayHeight * videoAspectRatio;
      offsetX = (constraints.maxWidth - displayWidth) / 2;
    } else {
      displayWidth = constraints.maxWidth;
      displayHeight = displayWidth / videoAspectRatio;
      offsetY = (constraints.maxHeight - displayHeight) / 2;
    }

    return Positioned(
      left: offsetX,
      top: offsetY,
      width: displayWidth,
      height: displayHeight,
      child: RepaintBoundary(
        child: CustomPaint(
          painter: DetectionPainter(
            detections: _currentDetections,
            imageWidth: videoWidth,
            imageHeight: videoHeight,
          ),
        ),
      ),
    );
  }

  String _formatDuration(Duration duration) {
    final minutes = duration.inMinutes;
    final seconds = duration.inSeconds % 60;
    return '${minutes.toString().padLeft(2, '0')}:${seconds.toString().padLeft(2, '0')}';
  }

  @override
  void dispose() {
    _stopDetection();
    _stopAudioSync();
    _stopSubtitleSync();
    _hideControlsTimer?.cancel();
    _volumePopupController.dispose();
    _speedPopupController.dispose();
    _videoPlayer.dispose();
    _audioPlayer.dispose();
    _detectionPlayer.dispose();
    _detector.dispose();
    _mainFocusNode.dispose();
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);
    super.dispose();
  }
}
