class VideoStreamModel {
  final String? content;
  final int? width;
  final int? height;
  final int? fps;
  final String? resolution;
  final int? bitrate;

  VideoStreamModel({
    this.content,
    this.width,
    this.height,
    this.fps,
    this.resolution,
    this.bitrate,
  });

  factory VideoStreamModel.fromJson(Map<String, dynamic> json) {
    return VideoStreamModel(
      content: json['content'],
      width: json['width'],
      height: json['height'],
      fps: json['fps'],
      resolution: json['resolution'],
      bitrate: json['bitrate'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'content': content,
      'width': width,
      'height': height,
      'fps': fps,
      'resolution': resolution,
      'bitrate': bitrate,
    };
  }
}

class AudioStreamModel {
  final String? content;
  final String? locale;
  final String? trackType; // "ORIGINAL", "DUBBED", "DESCRIPTIVE", "SECONDARY"
  final String? trackName;

  AudioStreamModel({
    this.content,
    this.locale,
    this.trackType,
    this.trackName,
  });

  factory AudioStreamModel.fromJson(Map<String, dynamic> json) {
    return AudioStreamModel(
      content: json['content'],
      locale: json['locale'],
      trackType: json['trackType'],
      trackName: json['trackName'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'content': content,
      'locale': locale,
      'trackType': trackType,
      'trackName': trackName,
    };
  }
}

class SubtitlesStreamModel {
  final String? content;
  final String? locale;
  final bool? autoGenerated;

  SubtitlesStreamModel({
    this.content,
    this.locale,
    this.autoGenerated,
  });

  factory SubtitlesStreamModel.fromJson(Map<String, dynamic> json) {
    return SubtitlesStreamModel(
      content: json['content'],
      locale: json['locale'],
      autoGenerated: json['autoGenerated'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'content': content,
      'locale': locale,
      'autoGenerated': autoGenerated,
    };
  }
}
